spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mybankdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

server:
  error:
    include-stacktrace: never